// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgRPMqvPJMBkNYLztbNU4WNPVJEl5POnw',
    appId: '1:439513873786:web:b435aaafdef403482e2ac3',
    messagingSenderId: '439513873786',
    projectId: 'mamavault',
    authDomain: 'mamavault.firebaseapp.com',
    storageBucket: 'mamavault.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlvCuC8Z10iM9VoMbqhxA8BMF_3FNx1DU',
    appId: '1:439513873786:android:743d5cb1c40ef3f52e2ac3',
    messagingSenderId: '439513873786',
    projectId: 'mamavault',
    storageBucket: 'mamavault.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCImuA_y4T_YEInJX0uGO5OBiM8hpQauA',
    appId: '1:439513873786:ios:2e07f607af95dce42e2ac3',
    messagingSenderId: '439513873786',
    projectId: 'mamavault',
    storageBucket: 'mamavault.appspot.com',
    androidClientId: '439513873786-h5lbfq0eo8sg9828ih5rh0gn77nttvev.apps.googleusercontent.com',
    iosClientId: '439513873786-nd0tsgh2dalocp1bqnlb8o2k9rg2kp73.apps.googleusercontent.com',
    iosBundleId: 'com.example.mamavault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCImuA_y4T_YEInJX0uGO5OBiM8hpQauA',
    appId: '1:439513873786:ios:ebd670093eda3e1b2e2ac3',
    messagingSenderId: '439513873786',
    projectId: 'mamavault',
    storageBucket: 'mamavault.appspot.com',
    androidClientId: '439513873786-h5lbfq0eo8sg9828ih5rh0gn77nttvev.apps.googleusercontent.com',
    iosClientId: '439513873786-j8a4spe04is8aetb082gfejakv7lb7ft.apps.googleusercontent.com',
    iosBundleId: 'com.example.interrupt',
  );
}
